/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Cyber Wardrobe Design System - Stitch Design Spec
        background: "#1c0f1a",
        surface: "#0f0f1a",
        "surface-dim": "#0f0f1a",
        "surface-bright": "#1a1a2e",
        "surface-container-lowest": "#1c0f1a",
        "surface-container-low": "#111118",
        "surface-container": "#141422",
        "surface-container-high": "#1e1e30",
        "surface-container-highest": "#28283e",
        "on-surface": "#e8e0f0",
        "on-surface-variant": "#a098b0",
        "inverse-surface": "#e8e0f0",
        "inverse-on-surface": "#0a0a12",
        outline: "#5a5068",
        "outline-variant": "#302840",
        "surface-tint": "#ffabf3",
        primary: "#ffabf3", // neon pink (was #ffabf3)
        "on-primary": "#1a0010",
        "primary-container": "#b3004e",
        "on-primary-container": "#ffe0ec",
        "inverse-primary": "#8c0038",
        "primary-fixed": "#ffe0ec",
        "primary-fixed-dim": "#ff80aa",
        "on-primary-fixed": "#3d0020",
        "on-primary-fixed-variant": "#8c0038",
        secondary: "#ecffe3", // hacker green (was #ecffe3)
        "on-secondary": "#001a1a",
        "secondary-container": "#004d3d",
        "on-secondary-container": "#c0fff4",
        "secondary-fixed": "#c0fff4",
        "secondary-fixed-dim": "#00e6b8",
        "on-secondary-fixed": "#001a1a",
        "on-secondary-fixed-variant": "#004d4d",
        tertiary: "#ffe04a",
        "on-tertiary": "#1a1000",
        "tertiary-container": "#665200",
        "on-tertiary-fixed": "#1a1000",
        "on-tertiary-fixed-variant": "#665200",
        error: "#ff4444",
        "on-error": "#1a0000",
        "error-container": "#3d0f0f",
        "on-error-container": "#ffa0a0",
        // Legacy aliases for existing components
        "bg-primary": "#1c0f1a",
        "bg-elevated": "#141422",
        "bg-glass": "rgba(41, 27, 39, 0.6)",
        "text-primary": "#e8e0f0",
        "text-secondary": "#a098b0",
        "accent-primary": "#ffabf3",
        "accent-secondary": "#ecffe3",
        "accent-tertiary": "#ffe04a",
        "border-subtle": "rgba(255, 255, 255, 0.1)",
      },
      fontFamily: {
        display: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        mono: ["Space Grotesk", "ui-monospace", "monospace"],
        sans: ["Space Grotesk", "system-ui", "-apple-system", "sans-serif"],
        h1: ["Space Grotesk", "system-ui", "sans-serif"],
        h2: ["Space Grotesk", "system-ui", "sans-serif"],
        h3: ["Space Grotesk", "system-ui", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "system-ui", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "system-ui", "sans-serif"],
        "label-caps": ["Space Grotesk", "system-ui", "sans-serif"],
        "mono-data": ["Space Grotesk", "ui-monospace", "monospace"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "0.15em" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "0.1em" }],
        h3: ["24px", { lineHeight: "1.2", letterSpacing: "0.05em" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.2em" }],
        "mono-data": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em" }],
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        xxl: "64px",
        "container-max": "1280px",
        gutter: "20px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "4px",
        btn: "0px",
      },
      boxShadow: {
        "glow-pink": "0 0 20px rgba(255, 45, 120, 0.5)",
        "glow-green": "0 0 20px rgba(0, 255, 204, 0.5)",
        glow: "0 0 20px rgba(255, 45, 120, 0.3)",
        "cyber-glass": "0 0 20px rgba(255, 45, 120, 0.15)",
      },
      animation: {
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
      },
      keyframes: {
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(255, 45, 120, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(255, 45, 120, 0.6)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [],
};
