import { MarketTool, QuizQuestion, StyleQuadrant } from '@/types/marketplace';

export const MARKET_TOOLS: MarketTool[] = [
  {
    id: 'palm-reading',
    name: '手相趣味解读',
    nameEn: 'Palm & Face Reading',
    description: '上传一张手部照片，AI玄学大师即刻为您深度解读命理玄机。古籍风格趣味报告趣味与专业并存，十余项命理指标深度解析，带标注分析图让古老智慧可视化呈现。',
    icon: 'auto_awesome',
    price: 39,
    originalPrice: 129,
    category: 'fortune',
    features: ['10大命理分析点（生命/智慧/感情/事业/财运）', '古籍风格趣味报告，附原文出处', '带标注的手相分析可视化图', '玄学运势总评+改运建议', '可保存分享的专属命理档案'],
    isHot: true,
    isNew: true,
    color: '#ffabf3',
    coverImage: '/assets/marketplace-cover.png',
  },
  {
    id: 'style-analyzer',
    name: '风格测试',
    nameEn: 'Style Quiz',
    description: '15道趣味穿搭题，AI深度分析您的面部轮廓、五官量感、气质特征，精准定位您的专属风格象限。直线型还是曲线型？大量感还是小量感？明星同款风格分析，让穿搭从此不踩雷。',
    icon: 'checkroom',
    price: 19,
    originalPrice: 69,
    category: 'style',
    features: ['15道精选穿搭题，涵盖脸型/五官/气质/偏好', '4大风格象限精确定位（直线/曲线 × 大量感/小量感）', '明星风格参考对照，找到您的穿搭偶像', '专属穿搭颜色推荐（避雷色+推荐色）', '适合风格+不适合风格双列表'],
    isHot: true,
    color: '#ecffe3',
    coverImage: '/assets/marketplace-cover.png',
  },
  {
    id: 'lipstick-recommendation',
    name: '口红推荐',
    nameEn: 'Lipstick Finder',
    description: '上传一张自拍，AI美妆顾问即刻为您深度分析肤色冷暖与色调，从Dior、YSL、Armani、Chanel等顶级品牌中精准匹配最适合您的口红色号。支持人脸试色对比，场景标签帮您选对每一支。',
    icon: 'palette',
    price: 29,
    originalPrice: 99,
    category: 'lipstick',
    features: ['Dior/YSL/Armani/Chanel 四大品牌全覆盖', 'AI肤色冷暖分析（冷调/暖调/中性）', '3-5支精准色号推荐，含人脸试色对比', '场景标签（通勤/约会/派对/日常）', '质地建议（哑光/缎光/镜光）'],
    isHot: true,
    isNew: true,
    color: '#fbbf24',
    coverImage: '/assets/marketplace-cover.png',
  },
  {
    id: 'image-diagnosis',
    name: '个人形象诊断',
    nameEn: 'Image Diagnosis',
    description: '上传一张正面照，AI形象顾问为您提供全方位的个人形象诊断报告。精准判断您的四季类型与色调，6套穿搭示例图文并茂，妆容/发型/配饰一站式指导，瑞士网格高端排版可直接保存分享。',
    icon: 'face',
    price: 49,
    originalPrice: 169,
    category: 'image-diagnosis',
    features: ['四季类型精准诊断（春/夏/秋/冬）', '肤色冷暖与明暗对比度全面分析', '6套完整穿搭示例，含单品清单', '专业妆容指南（底妆/眼影/腮红/口红）', '发型发色推荐+配饰金属色系建议', '可分享的高端诊断报告，一键保存'],
    isHot: true,
    isNew: true,
    color: '#bfd043',
    coverImage: '/assets/marketplace-cover.png',
  },
  {
    id: 'seasonal-outfit',
    name: '四季穿搭指南',
    nameEn: 'Seasonal Outfit Guide',
    description: '上传正面或全身人物照片，AI生成一套高完成度的小红书风格四季韩系潮牌穿搭指南系列海报。保留人物真实辨识度，基于同一人分别模拟春夏秋冬四种色彩穿搭逻辑下的造型方案。',
    icon: 'calendar_month',
    price: 69,
    originalPrice: 199,
    category: 'outfit',
    features: ['韩系潮牌首尔街拍风格lookbook', '保留本人真实五官、脸型、身材比例', '四季色彩逻辑独立造型方案（春夏秋冬）', 'Hero主推造型+5-6套延展lookbook', '推荐色/慎用色/配色公式/单品建议', '顾问式总结+避雷提醒，可直接分享'],
    isHot: true,
    isNew: true,
    color: '#ff9f43',
    coverImage: '/assets/marketplace-cover.png',
  },
  {
    id: 'personal-color',
    name: '个人色彩分析',
    nameEn: 'Personal Color Analysis',
    description: '上传真人正面照片，AI制作高质感个人色彩分析报告资讯图表。清新高级手绘手帐风，精准分析肤色冷暖、四季类型、最适合颜色，并排对比展示不同颜色的上身效果。',
    icon: 'palette',
    price: 39,
    originalPrice: 129,
    category: 'color',
    features: ['精准分析肤色冷暖调（冷皮/暖皮/中性调）', '四季色彩类型细分（16型全覆盖）', '最适合/普通/不建议颜色对比展示', '专属色盘专业调色盘风格', '显白提气色/显老显脏颜色双提示', '妆容/发色/穿搭配色方向，手帐风海报可直接分享'],
    isHot: true,
    isNew: true,
    color: '#ff6b9d',
    coverImage: '/assets/marketplace-cover.png',
  },
];

export const CATEGORIES = [
  { id: 'all', name: '全部工具', icon: 'apps' },
  { id: 'fortune', name: '玄学解读', icon: 'auto_awesome' },
  { id: 'style', name: '风格测试', icon: 'checkroom' },
  { id: 'lipstick', name: '口红推荐', icon: 'palette' },
  { id: 'outfit', name: '穿搭指南', icon: 'calendar_month' },
  { id: 'color', name: '色彩分析', icon: 'palette' },
  { id: 'image-diagnosis', name: '形象诊断', icon: 'face' },
] as const;

export const STYLE_QUADRANTS: StyleQuadrant[] = [
  {
    id: 'straight-large',
    name: '直线型·大量感',
    line: '直线型',
    volume: '大量感',
    desc: '干练大气、硬汉气场',
    color: '#ecffe3',
    traits: ['硬汉', '沉稳', '大哥气场', '领袖气质'],
    celebrities: ['胡军', '彭于晏', '张涵予', '吴京'],
    suitableStyles: ['工装硬汉风', '轻熟商务', '暗黑机能', '美式复古', '老钱松弛'],
    suitableColors: ['黑色', '深灰', '军绿', '深蓝', '卡其'],
    avoidColors: ['粉红', '浅粉', '亮黄', '荧光色'],
    avoidStyles: ['柔软毛绒', '鲜艳颜色', '可爱风格'],
    recommendedItems: ['工装靴', '皮夹克', '直筒牛仔裤', '军绿色外套', '黑色皮鞋'],
  },
  {
    id: 'straight-small',
    name: '直线型·小量感',
    line: '直线型',
    volume: '小量感',
    desc: '清冷精致、高级少年感',
    color: '#bfd043',
    traits: ['清冷', '精致', '少年感+距离感', '高级'],
    celebrities: ['丁真', '王鹤棣', '吴磊', '陈坤'],
    suitableStyles: ['Urban休闲', 'Clean Fit', '日系', '盐系', '老钱松弛'],
    suitableColors: ['黑色', '白色', '灰色', '藏蓝', '军绿'],
    avoidColors: ['老年款颜色', '花色', '过于鲜艳'],
    avoidStyles: ['老年款', '宽松Oversized', '复杂图案'],
    recommendedItems: ['黑色打底', '直筒裤', '简约球鞋', '工装马甲', '白衬衫'],
  },
  {
    id: 'curve-small',
    name: '曲线型·小量感',
    line: '曲线型',
    volume: '小量感',
    desc: '温暖亲和、清新少年感',
    color: '#ffabf3',
    traits: ['暖男', '少年感', '亲和力', '清新'],
    celebrities: ['张国荣', '何炅', '林志颖', '王源'],
    suitableStyles: ['韩系盐系', '精致简约', '学院风', '文艺清新', '日系复古'],
    suitableColors: ['浅蓝', '白色', '米色', '浅灰', '淡粉'],
    avoidColors: ['纯黑', '深紫', '大红色'],
    avoidStyles: ['过于硬挺老干部风', '深沉暗黑风', '粗犷工装'],
    recommendedItems: ['白色T恤', '针织开衫', '休闲裤', '小白鞋', '学院风polo'],
  },
  {
    id: 'curve-large',
    name: '曲线型·大量感',
    line: '曲线型',
    volume: '大量感',
    desc: '大气慵懒、成熟有魅力',
    color: '#fbbf24',
    traits: ['大气', '慵懒', '有存在感', '幽默'],
    celebrities: ['沈腾', '沙溢', '黄晓明', '邓超'],
    suitableStyles: ['雅痞风', '复古文艺', '霸道总裁', '轻熟休闲', '老钱松弛'],
    suitableColors: ['深色系', '酒红', '墨绿', '深棕', '藏青'],
    avoidColors: ['臃肿的浅色', '荧光色'],
    avoidStyles: ['臃肿', '不修边幅', '过于紧身'],
    recommendedItems: ['西装外套', '直筒大衣', '修身长裤', '乐福鞋', '高领毛衣'],
  },
];

export const MOCK_ANALYSIS_RESULTS = {
  style: {
    quadrant: 'straight-large',
    faceShape: '鹅蛋脸',
    suitableStyles: ['商务休闲', '极简主义', '中性风', '都市通勤'],
    avoidStyles: ['甜美可爱', '波西米亚', '繁复宫廷'],
    suitableColors: ['黑白灰', '藏蓝', '军绿', '焦糖'],
    avoidColors: ['粉嫩马卡龙', '荧光色', '高饱和艳色'],
    celebrities: ['刘雯', '袁泉', '俞飞鸿'],
  },
  palmReading: {
    overallFortune: '紫微星动，命格清奇',
    overallRating: '上上签',
    summary: '观阁下掌纹，天纹地纹人纹三才齐备，五行调和，命带贵人。此掌相主人聪慧过人，事业有成，情感顺遂，财运亨通。古籍有云：「掌中有三奇，一生无虞虑。」阁下正是此等吉相。',
    points: [
      {
        name: '生命线',
        classicalTitle: '地纹·寿元',
        finding: '纹深且长，环绕大鱼际，无断裂杂纹',
        interpretation: '地纹绵长如江河，主寿元充沛，根基稳固。古籍《麻衣神相》有云：「地纹深长无断续，寿逾古稀不须疑。」阁下生命力旺盛，宜善养之。',
        fortune: '大吉',
      },
      {
        name: '智慧线',
        classicalTitle: '人纹·才思',
        finding: '纹路清晰，向掌心延伸，略呈弧形',
        interpretation: '人纹明朗如新月，主才思敏捷，过目不忘。《柳庄相法》载：「人纹如弓不杂乱，聪明智慧出人前。」阁下天资聪颖，宜以学立身。',
        fortune: '大吉',
      },
      {
        name: '感情线',
        classicalTitle: '天纹·情缘',
        finding: '纹路平直，末端分叉为二',
        interpretation: '天纹平直分双叉，主情路坦荡，一生有良缘相伴。《神相全编》曰：「天纹分叉情路顺，夫妻和睦享天伦。」阁下感情世界丰富多彩。',
        fortune: '吉',
      },
      {
        name: '事业线',
        classicalTitle: '玉柱纹·功名',
        finding: '自掌根直上，纹深且不间断',
        interpretation: '玉柱纹直冲中指，主功名早达，事业顺遂。《水镜神相》云：「玉柱通达无阻碍，一生事业自辉煌。」阁下仕途可期，宜把握机遇。',
        fortune: '大吉',
      },
      {
        name: '婚姻线',
        classicalTitle: '家纹·姻缘',
        finding: '小指下方横纹二条，平行等长',
        interpretation: '家纹双线齐平行，主姻缘美满，琴瑟和鸣。《太清神鉴》载：「家纹成双且平正，天作之合好姻缘。」阁下婚姻稳固，家庭和睦。',
        fortune: '吉',
      },
      {
        name: '财运线',
        classicalTitle: '财帛纹·禄位',
        finding: '无名指下方斜纹数条，纹路清晰',
        interpretation: '财帛纹多条且明，主财运亨通，日进斗金。《麻衣神相》云：「财纹条条皆明朗，一生富贵不须忙。」阁下财源广进，宜守正道。',
        fortune: '大吉',
      },
      {
        name: '健康线',
        classicalTitle: '养生纹·体魄',
        finding: '纹路细浅，自掌根向小指延伸',
        interpretation: '养生纹细而不乱，主体魄康健，少有疾厄。《神相铁关刀》曰：「养生纹细如丝线，百年无病自安然。」阁下注意养生之道即可长寿。',
        fortune: '中吉',
      },
      {
        name: '子女线',
        classicalTitle: '嗣纹·子息',
        finding: '婚姻线上方短线数条，清晰分明',
        interpretation: '嗣纹条条分明，主子息有靠，后代昌盛。《冰鉴》载：「嗣纹分明子孙旺，枝繁叶茂满堂春。」阁下后代可期，宜善加教诲。',
        fortune: '吉',
      },
      {
        name: '旅游线',
        classicalTitle: '驿马纹·行旅',
        finding: '手掌外缘弧线明显，向外延伸',
        interpretation: '驿马纹深且外展，主一生行遍天下，见识广博。《柳庄相法》云：「驿马纹深出海外，一生行遍五湖游。」阁下宜远行发展，他乡建功。',
        fortune: '小吉',
      },
      {
        name: '直觉线',
        classicalTitle: '灵纹·六感',
        finding: '月丘处弧线半圆，纹路隐隐可见',
        interpretation: '灵纹若隐若现，主六灵感应敏锐，洞悉先机。《太乙照神经》曰：「灵纹隐隐月丘现，未卜先知胜常人。」阁下灵觉超凡，宜信直觉。',
        fortune: '小吉',
      },
    ],
    ancientWisdom: '综合十相，阁下命格属「紫微贪狼」之格，主人精明能干、财运丰厚、感情圆满。古籍《推背图》有云：「天生我材必有用，千金散尽还复来。」此言正合阁下之命理。宜积善行德，则福泽绵长，一世无忧。',
  },
  lipstick: {
    skinTone: '暖黄偏白',
    skinToneEn: 'Warm Yellow Fair',
    undertone: '暖调',
    undertoneEn: 'Warm',
    brand: 'Dior',
    recommendedShades: [
      {
        name: '迪奥烈艳蓝金 #999',
        nameEn: 'Dior Rouge #999',
        shadeCode: '#999',
        hex: '#b5243b',
        finish: 'satin',
        matchScore: 98,
        sceneTags: ['约会', '年会', '重要场合'],
        description: '经典正红色，浓郁饱和，显白提气色，暖调肌肤的万能色。丝绒质感高级不拔干。',
      },
      {
        name: '迪奥烈艳蓝金 #720',
        nameEn: 'Dior Rouge #720',
        shadeCode: '#720',
        hex: '#c46b5c',
        finish: 'velvet',
        matchScore: 95,
        sceneTags: ['日常通勤', '咖啡约会', '周末逛街'],
        description: '温柔奶茶玫瑰色，薄涂日常感十足，厚涂气质优雅。不挑场合的百搭之选。',
      },
      {
        name: '迪奥烈艳蓝金 #840',
        nameEn: 'Dior Rouge #840',
        shadeCode: '#840',
        hex: '#a04832',
        finish: 'matte',
        matchScore: 92,
        sceneTags: ['秋冬日常', '办公室', '商务场合'],
        description: '复古砖红色，高级感拉满，搭配大衣和毛衣的氛围感色。暖皮秋冬必入。',
      },
      {
        name: '迪奥魅惑润唇膏 #006',
        nameEn: 'Dior Addict #006',
        shadeCode: '#006',
        hex: '#d4836e',
        finish: 'glossy',
        matchScore: 88,
        sceneTags: ['素颜出门', '运动健身', '自然日常'],
        description: '蜜桃珊瑚色，水润质地，素颜涂也自然好看。春夏使用效果最佳。',
      },
      {
        name: '迪奥烈艳蓝金 #772',
        nameEn: 'Dior Rouge #772',
        shadeCode: '#772',
        hex: '#8b4a5e',
        finish: 'satin',
        matchScore: 85,
        sceneTags: ['晚宴', '派对', '秋冬约会'],
        description: '浆果紫红色，显贵气又时髦，适合搭配精致妆容。晚间的绝佳选择。',
      },
    ],
    summaryAdvice: '根据您的暖黄偏白肤色分析，Dior烈艳蓝金系列中#999正红和#720奶茶玫瑰最为推荐。#999是永不过时的经典，适合所有重要场合；#720则是日常通勤的最佳伴侣。建议秋冬选择哑光质地（#840砖红），春夏选择水润质地（#006珊瑚）。避免过于偏粉的冷调色号，容易显黑。',
  },
  imageDiagnosis: {
    seasonType: '秋季型',
    seasonTypeEn: 'Autumn',
    toneType: '暖调',
    toneTypeEn: 'Warm',
    brightness: '中明度',
    brightnessEn: 'Medium',
    contrast: '中对比度',
    contrastEn: 'Medium Contrast',
    colorPalette: [
      { name: '焦糖棕', hex: '#a0693e', category: 'best' },
      { name: '砖红色', hex: '#a04832', category: 'best' },
      { name: '芥末黄', hex: '#c9a227', category: 'best' },
      { name: '橄榄绿', hex: '#6b7c3e', category: 'best' },
      { name: '奶油白', hex: '#f5f0e6', category: 'good' },
      { name: '驼色', hex: '#c4a882', category: 'good' },
      { name: '深蓝', hex: '#2d4a6f', category: 'good' },
      { name: '薄荷绿', hex: '#98c1a9', category: 'good' },
      { name: '荧光粉', hex: '#ff6eb4', category: 'avoid' },
      { name: '电光蓝', hex: '#00bfff', category: 'avoid' },
      { name: '亮紫色', hex: '#bf5fff', category: 'avoid' },
      { name: '冰灰色', hex: '#c8d0d8', category: 'avoid' },
    ],
    outfitExamples: [
      {
        occasion: '通勤办公',
        description: '驼色西装外套 + 奶油白真丝衬衫 + 深蓝直筒裤 + 焦糖棕乐福鞋',
        items: ['驼色西装外套', '奶油白真丝衬衫', '深蓝直筒裤', '焦糖棕乐福鞋'],
      },
      {
        occasion: '周末休闲',
        description: '橄榄绿针织毛衣 + 米白阔腿裤 + 芥末黄帆布鞋 + 棕色皮质托特包',
        items: ['橄榄绿针织毛衣', '米白阔腿裤', '芥末黄帆布鞋', '棕色皮质托特包'],
      },
      {
        occasion: '约会晚餐',
        description: '砖红色缎面吊带裙 + 焦糖棕西装外套 + 金色细带高跟 + 复古金色耳环',
        items: ['砖红色缎面吊带裙', '焦糖棕西装外套', '金色细带高跟', '复古金色耳环'],
      },
      {
        occasion: '户外旅行',
        description: '芥末黄风衣 + 奶油白T恤 + 深蓝牛仔裤 + 驼色短靴 + 棕色棒球帽',
        items: ['芥末黄风衣', '奶油白T恤', '深蓝牛仔裤', '驼色短靴', '棕色棒球帽'],
      },
      {
        occasion: '朋友聚会',
        description: '焦糖棕皮衣 + 黑色高领打底 + 橄榄绿百褶裙 + 黑色短靴 + 金色项链',
        items: ['焦糖棕皮衣', '黑色高领打底', '橄榄绿百褶裙', '黑色短靴', '金色项链'],
      },
      {
        occasion: '正式场合',
        description: '深蓝修身西装套装 + 奶油白衬衫 + 砖红色领带/丝巾 + 棕色牛津鞋',
        items: ['深蓝修身西装套装', '奶油白衬衫', '砖红色领带/丝巾', '棕色牛津鞋'],
      },
    ],
    makeupGuide: [
      '底妆：选择暖调象牙白粉底，避免偏粉偏白的冷调色号',
      '眼影：以焦糖棕、暖铜色为主色调，叠加深棕色加深眼尾',
      '腮红：蜜桃杏色或温暖珊瑚色，轻扫颧骨上方自然过渡',
      '口红：砖红色、焦糖玫瑰、奶茶色最适配，避免荧光粉和冷调玫红',
      '眉毛：使用灰棕色眉笔，自然填充避免生硬线条',
      '高光：选择香槟金色高光，点缀颧骨和鼻梁中央',
    ],
    hairAdvice: [
      '发色推荐：焦糖棕、栗子棕、蜂蜜茶棕，与暖调肤色和谐统一',
      '避免：冷灰调银白色、铂金色、冷调亚麻色',
      '卷度建议：自然微卷或大波浪卷，增加柔和感和女人味',
      '发型推荐：中长锁骨发搭配空气刘海，修饰脸型且显气质',
      '护理建议：每月深层护理一次，保持发丝光泽感',
    ],
    accessoryAdvice: [
      '金属色系：金色、玫瑰金最适配，避免银色和铂金色',
      '包包：驼色、焦糖棕、砖红色皮质包包为首选',
      '鞋子：棕色系乐福鞋、焦糖色短靴百搭且高级',
      '围巾：芥末黄、焦糖色、驼色羊绒围巾，秋冬氛围感拉满',
      '眼镜：玳瑁色或棕色镜框，温暖复古与整体造型统一',
    ],
    overallSummary: '您的形象诊断为「秋季型·暖调·中明度·中对比度」，整体风格温暖、沉稳、有高级感。核心穿搭关键词是「大地色系」——焦糖棕、砖红、芥末黄、橄榄绿是您的四大守护色。妆容上坚持暖调路线，发色选择暖棕色系，配饰以金色和棕色皮质为主。避免冷调荧光色和冰灰色系，它们会与您的自然肤色产生冲突。建议建立以驼色和奶油白为基色的胶囊衣橱，搭配暖调彩色单品即可轻松打造高级感。',
  },
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: '您的脸型整体轮廓更接近哪种？',
    options: [
      { text: '棱角分明，下颌线清晰', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '线条柔和，脸部圆润', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '额头宽，下巴尖', lineScore: 1, curveScore: 1, volumeScore: 0 },
      { text: '脸部各部分都比较均衡', lineScore: 1, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 2,
    question: '您的五官给人的第一感觉是？',
    options: [
      { text: '深邃、立体、攻击性强', lineScore: 2, curveScore: 0, volumeScore: 2 },
      { text: '柔和、温暖、无距离感', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '精致、清冷、高级感', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '亲切、自然、接地气', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 3,
    question: '您更适合哪种风格的衣服？',
    options: [
      { text: '硬挺的皮衣、工装', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '柔软的针织、毛衣', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '简约的白衬衫、纯色T恤', lineScore: 1, curveScore: 1, volumeScore: 0 },
      { text: '休闲的卫衣、牛仔裤', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 4,
    question: '您希望给别人留下什么印象？',
    options: [
      { text: '成熟、可靠、有领导力', lineScore: 1, curveScore: 0, volumeScore: 2 },
      { text: '温暖、亲切、好相处', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '时尚、高级、有品位', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '随性、慵懒、有魅力', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 5,
    question: '您喜欢哪种颜色的衣服？',
    options: [
      { text: '黑色、深灰、军绿', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '白色、浅蓝、米色', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '黑白灰，无色彩系', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '酒红、墨绿、深棕', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 6,
    question: '您的身材属于哪种类型？',
    options: [
      { text: '高大、魁梧、有存在感', lineScore: 1, curveScore: 0, volumeScore: 2 },
      { text: '中等、精瘦、少年感', lineScore: 1, curveScore: 1, volumeScore: 0 },
      { text: '高大但偏瘦', lineScore: 1, curveScore: 1, volumeScore: 1 },
      { text: '中等偏壮（肩宽或胯宽）', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 7,
    question: '您平时喜欢什么风格的装修/环境？',
    options: [
      { text: '工业风、暗黑系', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '北欧风、简约白', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '极简主义、断舍离', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '复古文艺、混搭', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 8,
    question: '您更喜欢哪种明星风格？',
    options: [
      { text: '胡军、吴京式硬汉', lineScore: 2, curveScore: 0, volumeScore: 2 },
      { text: '张国荣、林志颖式暖男', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '王鹤棣、丁真式清冷', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '黄晓明、沈腾式雅痞', lineScore: 0, curveScore: 1, volumeScore: 2 },
    ],
  },
  {
    id: 9,
    question: '您觉得自己的气质更接近？',
    options: [
      { text: '大哥/领导', lineScore: 2, curveScore: 0, volumeScore: 2 },
      { text: '学长/暖男', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '清冷男神/氛围感', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '幽默有魅力的大叔', lineScore: 0, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 10,
    question: '如果去约会，您会穿什么？',
    options: [
      { text: '皮夹克+牛仔裤，帅气逼人', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '白衬衫+针织衫，温暖干净', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '黑色高领+直筒裤，简约高级', lineScore: 2, curveScore: 0, volumeScore: 0 },
      { text: '西装外套，成熟有魅力', lineScore: 0, curveScore: 1, volumeScore: 2 },
    ],
  },
  {
    id: 11,
    question: '您的肤色更接近哪种？',
    options: [
      { text: '很白，冷调偏粉', lineScore: 0, curveScore: 0, volumeScore: 0 },
      { text: '偏黄/暖调，自然肤色', lineScore: 0, curveScore: 0, volumeScore: 0 },
      { text: '小麦色/健康肤色', lineScore: 0, curveScore: 0, volumeScore: 0 },
      { text: '偏黑，深肤色', lineScore: 0, curveScore: 0, volumeScore: 0 },
    ],
  },
  {
    id: 12,
    question: '您平时买衣服的预算大概是？',
    options: [
      { text: '单件100元以内，性价比优先', lineScore: 0, curveScore: 1, volumeScore: 0 },
      { text: '单件100-300元，实用为主', lineScore: 1, curveScore: 1, volumeScore: 1 },
      { text: '单件300-600元，愿意为质感买单', lineScore: 2, curveScore: 1, volumeScore: 1 },
      { text: '单件600元以上，品质最重要', lineScore: 2, curveScore: 0, volumeScore: 2 },
    ],
  },
  {
    id: 13,
    question: '您的职业场景更接近？',
    options: [
      { text: '互联网/创意/时尚行业', lineScore: 1, curveScore: 1, volumeScore: 0 },
      { text: '金融/法律/传统商务', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '学生/自由职业/创业', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '制造/销售/服务业', lineScore: 1, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 14,
    question: '您更在意穿得舒服还是穿得好看？',
    options: [
      { text: '舒服第一，好看第二', lineScore: 0, curveScore: 2, volumeScore: 0 },
      { text: '好看和舒服同样重要', lineScore: 1, curveScore: 1, volumeScore: 1 },
      { text: '好看第一，舒服可以妥协', lineScore: 2, curveScore: 0, volumeScore: 1 },
      { text: '场合需要什么就穿什么', lineScore: 1, curveScore: 1, volumeScore: 1 },
    ],
  },
  {
    id: 15,
    question: '您对护肤/发型的投入程度是？',
    options: [
      { text: '基本不做，最多洗个头出门', lineScore: 0, curveScore: 0, volumeScore: 0 },
      { text: '偶尔打理，重要场合会注意', lineScore: 1, curveScore: 1, volumeScore: 0 },
      { text: '经常护理，有固定打理流程', lineScore: 1, curveScore: 1, volumeScore: 1 },
      { text: '每天认真护肤+发型，定制造型', lineScore: 2, curveScore: 1, volumeScore: 1 },
    ],
  },
];

export function calculateQuadrant(lineScore: number, curveScore: number, volumeScore: number): StyleQuadrant {
  const isLine = lineScore > curveScore;
  const isLarge = volumeScore >= 3;

  if (isLine && isLarge) return STYLE_QUADRANTS[0];
  if (isLine && !isLarge) return STYLE_QUADRANTS[1];
  if (!isLine && !isLarge) return STYLE_QUADRANTS[2];
  return STYLE_QUADRANTS[3];
}
